language: generic

go:
  - 1.13

os: linux
dist: bionic

services:
  - docker

# note before_deploy will run before each deploy provider
before_deploy:
  - . ./ci/package.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: ci/assets/*
  file_glob: true
  on:
    tags: true
    repo: $GITHUB_ORG/$GITHUB_REPO
