# (C) Copyright IBM Corporation 2019, 2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#Kabanero! on activate substitute Digest for text '@Digest@'
# This pipeline will build the source repo, optionally sign the image built, push the image to the image registry,
# scan the built image, and optionally promote the deployment data to a gitops repo.  
# The pipeline will also do a local deployment if webhooks-tekton-local-deploy is set to true.
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-push-promote-pl-@Digest@
spec:
  params:
  - name: webhooks-tekton-local-deploy
    type: string
  - name: docker-imagename
    type: string
  - name: docker-imagetag
    type: string
  - name: git-project
    type: string
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: build-push-promote-task
    taskRef:
      name: build-push-promote-task-@Digest@
    params:
      - name: docker-imagename
        value: "$(params.docker-imagename)"
      - name: docker-imagetag
        value: "$(params.docker-imagetag)"
      - name: git-project
        value: "$(params.git-project)"
    resources:
      inputs:
      - name: git-source
        resource: git-source
      outputs:
      - name: docker-image
        resource: docker-image
      - name: git-source
        resource: git-source
  - name: image-scan-task
    taskRef:
      name: image-scan-task-@Digest@
    runAfter: [build-push-promote-task]
    params:
      - name: docker-imagename
        value: "$(params.docker-imagename)"
      - name: docker-imagetag
        value: "$(params.docker-imagetag)"
    resources:
      inputs:
      - name: git-source
        resource: git-source
      - name: docker-image
        resource: docker-image
  - name: deploy-task
    conditions:
    - conditionRef: deployment-condition-@Digest@
      params:
      - name: webhooks-tekton-local-deploy
        value: $(params.webhooks-tekton-local-deploy)
    taskRef:
      name: deploy-task-@Digest@
    runAfter: [image-scan-task]
    params:
      - name: docker-imagename
        value: "$(params.docker-imagename)"
      - name: docker-imagetag
        value: "$(params.docker-imagetag)"
    resources:
      inputs:
      - name: git-source
        resource: git-source
        from: [build-push-promote-task]
      - name: docker-image
        resource: docker-image
