#Kabanero! on activate substitute Digest for text '@Digest@'
#
# This pipeline will build the source in the git-source repo and create a local image specified in the docker-image resource.
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pl-@Digest@
spec:
  params:
    - name: repo-url
      type: string
    - name: gitrevision
      type: string
    - name: image
      type: string
    - name: devfile
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: fetch-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.gitrevision)
        - name: subdirectory
          value: repo
    - name: fetch-dockerfile
      taskRef:
        name: fetch-dockerfile-@Digest@
      runAfter:
        - fetch-repository
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: devfileUrl
          value: '$(params.devfile)'
    - name: build-and-push
      taskRef:
        name: buildah-@Digest@
      runAfter:
        - fetch-dockerfile
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: '$(params.image):$(tasks.fetch-repository.results.commit)'
        - name: CONTEXT
          value: repo/
