#Kabanero! on activate substitute Digest for text '@Digest@'
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-dockerfile-@Digest@
spec:
  workspaces:
    - name: source
      mountPath: /source
  params:
    - name: devfileUrl
      description: Stack url for devfile
    - name: devfilePath
      default: repo/devfile.yaml
    - name: dockerfilePath
      default: Dockerfile
  steps:
    - name: fetch-dockerfile
      image: icp4apps/pipelines-utils:latest
      script: |
        DEVFILE_URL="$(params.devfileUrl)"
        DOCKERFILE_PATH="$(workspaces.source.path)/$(params.dockerfilePath)"
        DEVFILE="$(workspaces.source.path)/devfile.yaml"

        wget -O $DEVFILE $DEVFILE_URL
        yq -r . $DEVFILE

        LOOKUP='.metadata."alpha.build-dockerfile"'
        DOCKERFILE_URL=$(yq -r $LOOKUP $DEVFILE)

        # Fetch dockerfile
        wget -O $DOCKERFILE_PATH $DOCKERFILE_URL
        cat $DOCKERFILE_PATH
