#!/bin/bash


export utility_script_enforce_stack_policy_path=pipelines/docker/pipelines-utils/scripts/enforce_stack_policy.sh
export utility_script_enforce_deploy_stack_policy_path=pipelines/docker/pipelines-utils/scripts/enforce_deploy_stack_policy.sh